### PR TITLE
removing the hardcoded pageurl for android

### PR DESCRIPTION
**Pull request by roshan04**
Fixing the issue of session not running on https server for android. Have removed the hardcoded pageurl.

### CODE REVIEW

**Comment by miherlosev** [comment]
Hi @roshan04 

Thank you for your contribution to TestCafe. We will review this PR.

**Comment by AndreyBelym** [comment]
Hi @roshan04, this part is required to avoid an issue that causes a browser to disconnect at the start:
https://github.com/DevExpress/testcafe/issues/2318

Could you please describe your use case with more details and provide an example that can be used to reproduce the problem with HTTPS?

**Comment by AndreyBelym** [comment]
I cannot accept this PR without some discussion. Since there was no activity for a long time, I close it for housekeeping purposes. Please contact me via GitHub/email so we can reopen the PR.

**Comment by roshan04** [comment]
I apologize for the inactivity in the thread for pull request.
Can we please open it for further discussion. Want to know the concern from your end , how the changes in this pull request will affect the current flow for testcafe-browser-provider-browserstack, so that I can come up with a non-breaking solution.

**Comment by miherlosev** [comment]
Hi @roshan04,

Please refer to [https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/154#issuecomment-908301331](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/154#issuecomment-908301331).
The changes in your PR will make the test run fail because some Android browsers request the connection URL twice.
Also, the PR should contain an issue description and a test for the fixed behavior.

**Comment by roshan04** [comment]
The problem we are solving through this PR is that the Browserstack users are not able to run Testcafe server in HTTPS for android devices. As in the current master branch the testcafe server is hardcoded to run in HTTP. I have removed the android check in this PR and could achieve the requirement of the users.

**Comment by miherlosev** [comment]
@roshan04

Thank you for the detailed description.
As described in [https://github.com/DevExpress/testcafe/issues/2318](https://github.com/DevExpress/testcafe/issues/2318), this code was added to fix browser disconnection in Android devices. We cannot remove it.
You need to rewrite the calculation of the connection URL [here](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/466ded007f965e4478ca3c954c7360a87c299806/src/browser-proxy.js#L21) and add tests for an Android device in case of HTTP and HTTPS protocols. If you can do it, please update this PR. If not, use the forked version of TestCafe.

**Comment by roshan04** [comment]
Thanks @miherlosev , will explore the code and will get to a non-breaking solution here.

**Pull request closed without merging**
