### PR TITLE
Added filter for chrome & firefox browsers

### PR DESCRIPTION
**Pull request by Archish27**
**Filtering chrome & firefox browser version > 53.0**

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@Archish27
Hello.
What issue do you try to solve by this PR? What do you need to filter out these browser versions?

**Comment by Archish27** [comment]
> @Archish27
> Hello.
> What issue do you try to solve by this PR? What do you need to filter out these browser versions?

Hi Alex,
Some of versions of chrome & firefox below 53.0 are causing hang up in browserstack. So, we filtering browsers to show chrome & firefox versions above 53.0

**Comment by Archish27** [comment]
@AlexKamaev Can you please review?

**Comment by AlexanderMoiseev** [comment]
Hello,

Thank you for pointing to the “browser versions” problem - we will consider documenting minimal supported browser versions. Please refer to this [thread](https://github.com/DevExpress/testcafe/issues/5228) for further correspondence .

**Pull request closed without merging**
