### PR TITLE
Read capabilities from a config file.

### PR DESCRIPTION
**Pull request by yashLadha**
This is becasue adding environment variables, every time for
any new capabilities it is very cumbersom and not a good
experience

### CODE REVIEW

**Comment by yashLadha** [comment]
@AndreyBelym can this be merged?

**Comment by yashLadha** [comment]
Let me refactor it to simplify some stuff. Cheers

**Comment by yashLadha** [comment]
We can always use require for `JSON` files but the problem with that is we don't always know that the user-supplied a valid JSON and it is existing or not. Environment name can be discussed but functionality wise I think this refactored approach covers almost all cases.

**Comment by yashLadha** [comment]
@miherlosev @AndreyBelym

**Comment by AndreyBelym** [comment]
We can leave error handling to `require`. I think its better to catch errors produced by `require` and add something like `Cannot load a capabilities config file from ${BROWSERSTACK_CAPABILITIES_CONFIG_PATG}: ${ORIGINAL_ERROR_STACKTRACE}`. The refactored code still looks quite complex for me.

**Comment by yashLadha** [comment]
I don't think these complexities should be bothered. As code is self-explanatory. and I don't want that if the user passed a txt and require throws error because of this.

**Comment by AndreyBelym** [comment]
GitHub statuses are not updated but tests pass for the last commit: [Build 665978781](https://travis-ci.org/github/testcafe-build-bot/testcafe-browser-provider-browserstack/builds/665978781).

Thank you for your contribution. Wrapping native callback-based functions with Promises can be a hard task. We want to avoid it if possible. So I still prefer to use `require` for this task. Also, we need to document it before releasing a new stable build.

**Pull request merged**
