### PR TITLE
fix screenshot error on landscape orientation

### PR DESCRIPTION
**Pull request by richardhendricksen**
Fix for issue mentioned in #148

### CODE REVIEW

**Comment by richardhendricksen** [comment]
close for now, since the fix doesn't work for Android tablets

**Comment by richardhendricksen** [comment]
after some testing it seems the screenshot rotation only applies to iOS devices. Updated PR to only rotate back when it's an iOS device

**Comment by wentwrong** [comment]
Thank you for your contribution, but I don't think that the proposed solution is exhaustive. Let's discuss it in the context of DevExpress/testcafe-browser-provider-browserstack#148 first.

**Comment by wentwrong** [comment]
After discussing the problem in #148, we decided to close it.

**Pull request closed without merging**
