### PR TITLE
Added ability to pass proxy options via environment variables

### LINKED ISSUE #6: Need proxy configuration options
I do not see any Browserstack configuration options to setup a proxy. I have a need for that due to network rules that do not allow communication between our internal network and Browserstack. Other applications we have get around this with Browserstack using an internal proxy and setting the appropriate configuration options. I'd be happy to submit a PR but I want to make sure the configuration is done correctly for this provider.

Thanks!

### PR DESCRIPTION
**Pull request by drobannx**
Updated README as well explaining how to use these options.

This resolves #6

### CODE REVIEW

**Comment by drobannx** [comment]
No problem. I am happy to help. What is the process for getting a new minor release published?

**Comment by AndreyBelym** [comment]
I'm going to publish it today, after some other guys from TestCafe team will review it.

**Comment by drobannx** [comment]
Sounds great. Thanks for the quick response!

**Comment by AndreyBelym** [comment]
Sorry for the delay, `testcafe-browser-provider-browserstack@1.1.0` was published to `npm`.

**Comment by drobannx** [comment]
@AndreyBelym Thanks for publishing this so quickly! 

However I did notice that the changes made in #8, force the proxy string to require a username and password. Username/passwords aren't not always required by proxies (in my case). For now I have got around it by putting a dummy username/password in but in those cases, I think it'd be better to accept the proxy string with just hostname:port or just the hostname since Browserstack Local will default the port to `3128` if not provided.

Thanks again for looking at this so quickly. It is much appreciated!

**Comment by AndreyBelym** [comment]
It's a bug introduced by me. I will fix it asap.

**Pull request merged**
