### PR TITLE
Set display resolution

### LINKED ISSUE #12: change the resolution
Hi,
I'm not sure if this is the right place to ask this question. 
Is there a way to change the resolution of the browser with this plugin?
We try to run our e2e tests with your plugin against browserstack and 
the only problem is at the moment that the screen is too small.

### PR DESCRIPTION
**Pull request by Lukas-Kullmann**
Since #34 and #35 did not have progress in almost three weeks, here is a PR that basically fixes the issue.

This PR fixes #12.

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Hi @Lukas-Kullmann, I'm sorry for delays, I'll try to address it next week.

**Comment by Lukas-Kullmann** [comment]
@AndreyBelym any progress on this?

**Comment by AndreyBelym** [comment]
Thanks for the help, I've merged it as a part of #44.

**Comment by Lukas-Kullmann** [comment]
Thank you. Could you create a new release for that?

**Comment by AndreyBelym** [comment]
@Lukas-Kullmann, I've just published `v1.5.0`, thank you again for waiting!

**Pull request closed without merging**
